### ISSUE TITLE
Safari skips elements and scroll with lags

### ISSUE THREAD

**Issue by spacepolice10** [oleggrishechkin/react-viewport-list#36]
Hi, nice library. Glad to see someone keep trying to create something great in terms of virtualisation of lists.

Have you tested your library on Safari? No matter what kind of content I put into ViewportList, Safari scrolls them incorrectly. Browser ALWAYS skip elements and throws you around the list in some unexpected places. Is there a way to fix it? It happens when you not provide ViewportRef

**Comment by spacepolice10** [comment]
Ok, i provided viewportRef with element which has height 100vh and overflow-y-scroll. Now all the elements always go to the top. As soon as i reload page component scrolls to the top extremely fast and laggy

**Comment by oleggrishechkin** [comment]
Hi, I tested it in safari (desktop and event mobile safari). The main cons of this browsers is unsupport of overflow-anchor css property. I need to compensate scroll manually. That's why viewportRef is required - if you don't provide it library will use documeny.body and scroll container. I'll try to test safari again.

Can you share your workaround? Component code and styles. (codesandbox/or video will be really helpful too)

**Comment by oleggrishechkin** [comment]
I tested. Everything is work as expected for me.

Workaround:

```typescript jsx
import {memo, useRef} from "react";
import {ViewportList} from "react-viewport-list";
import "./App.css";

const generateItems = (count: number) => new Array(count).fill(null).map((_, index) => ({
    id: index,
    title: index + 1,
    odd: index % 2 !== 0,
    // random height from 42px to 200px
    height: Math.round(Math.random() * (200 - 42) + 42),
    // random margin from 0px to 32px
    margin: Math.round(Math.random() * (32 - 0) + 0),
}));

const generatedItems = generateItems(1000);

const Item = memo(({item}: any) => (
    <div className={`item${item.odd ? ' odd' : ''}`}
         style={{ height: item.height, minHeight: item.height, maxHeight: item.height, marginBottom: item.margin }}>
        {item.title}
    </div>
));

const App = () => {
    const ref = useRef(null);

    return (
        <div className="list" ref={ref}>
            <ViewportList
                viewportRef={ref}
                items={generatedItems}
                initialIndex={999}
            >
                {(item) => (
                    <Item key={item.id} item={item}/>
                )}
            </ViewportList>
        </ScrollContainer>
    );
};

export default App;
```

./App.css
```css
.list {
    box-sizing: border-box;
    height: 100vh;
    width: 100vw;
    padding: 0 1rem;
    display: flex;
    flex-direction: column;
    overflow-x: hidden;
    overflow-y: scroll;
    background: black;
    will-change: transform;
}

@supports(height: 100dvh) {
    .list {
        height: 100dvh;
    }
}

.item {
    flex: 0 0 auto;
    padding: 1rem;
    border-radius: 1rem;
    background-color: rgb(44, 44, 46);
    overflow: hidden;
    max-width: 75%;
    min-width: 55%;
    min-height: 42px;
    box-sizing: border-box;
    align-self: flex-start;
}

.item.odd {
    align-self: flex-end;
    background-color: rgb(10, 132, 255);
}

.item.key {
    align-self: stretch;
}
```
